trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'
- script: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
  displayName: 'Install Rust'
- script: |
    rustc --version --verbose
    cargo --version --verbose
  displayName: 'Print Rust and Cargo Versions'
- script: |
    cd electron
    npm install
    npm build
    npm run dist -- --out $(Build.ArtifactStagingDirectory)
  displayName: 'Build App'
- task: PublishBuildArtifacts@1
  displayName: 'Upload Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'rust-electron'
    publishLocation: 'Container'
