[package]
name = "rust_electron"
version = "0.1.0"
authors = ["daose <bychen@edu.uwaterloo.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.3"
num-complex = "0.2"
